import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ArrowUpRight, Filter, RefreshCw } from "lucide-react";

export const metadata = {
  title: "Recommendations | ByOsaz Dashboard",
};

const recommendations = [
  {
    id: 1,
    product: "Hydrating Serum",
    confidence: 98,
    skinType: "Dry",
    ingredients: ["Hyaluronic Acid", "Glycerin", "Niacinamide"],
    status: "active",
    date: "2025-04-10",
  },
  {
    id: 2,
    product: "Oil Control Moisturizer",
    confidence: 95,
    skinType: "Oily",
    ingredients: ["Salicylic Acid", "Green Tea Extract", "Zinc PCA"],
    status: "active",
    date: "2025-04-10",
  },
  {
    id: 3,
    product: "Gentle Cleanser",
    confidence: 92,
    skinType: "Sensitive",
    ingredients: ["Ceramides", "Aloe Vera", "Chamomile"],
    status: "pending",
    date: "2025-04-09",
  },
  {
    id: 4,
    product: "Anti-Aging Cream",
    confidence: 94,
    skinType: "Mature",
    ingredients: ["Retinol", "Peptides", "Vitamin C"],
    status: "active",
    date: "2025-04-09",
  },
  {
    id: 5,
    product: "Brightening Toner",
    confidence: 90,
    skinType: "Combination",
    ingredients: ["Alpha Arbutin", "Licorice Root", "Vitamin B3"],
    status: "inactive",
    date: "2025-04-08",
  },
];

const getStatusColor = (status: string) => {
  switch (status) {
    case 'active':
      return 'bg-green-500 hover:bg-green-600';
    case 'pending':
      return 'bg-yellow-500 hover:bg-yellow-600';
    case 'inactive':
      return 'bg-red-500 hover:bg-red-600';
    default:
      return 'bg-gray-500 hover:bg-gray-600';
  }
};

export default function RecommendationsPage() {
  return (
    <DashboardLayout>
      <div className="space-y-8">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Product Recommendations</h1>
            <p className="text-muted-foreground">
              AI-powered skincare product recommendations based on user profiles
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Button variant="outline" size="icon">
              <Filter className="h-4 w-4" />
            </Button>
            <Button variant="outline" size="icon">
              <RefreshCw className="h-4 w-4" />
            </Button>
            <Button className="bg-osaz-red hover:bg-osaz-red/90 text-white">
              Generate New
            </Button>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-sm font-medium">Total Recommendations</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">15,728</div>
              <div className="flex items-center text-sm text-green-600 mt-1">
                <ArrowUpRight className="mr-1 h-4 w-4" />
                <span>+8% from last month</span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-sm font-medium">Average Confidence</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">94.3%</div>
              <div className="flex items-center text-sm text-green-600 mt-1">
                <ArrowUpRight className="mr-1 h-4 w-4" />
                <span>+2.1% from last month</span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-sm font-medium">Active Products</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">1,284</div>
              <div className="flex items-center text-sm text-green-600 mt-1">
                <ArrowUpRight className="mr-1 h-4 w-4" />
                <span>+24 new products</span>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Recommendations Table */}
        <Card>
          <CardHeader>
            <CardTitle>Recent Recommendations</CardTitle>
            <CardDescription>
              Latest product recommendations generated by our AI
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="rounded-md border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Product</TableHead>
                    <TableHead>Confidence</TableHead>
                    <TableHead>Skin Type</TableHead>
                    <TableHead>Key Ingredients</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Date</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {recommendations.map((rec) => (
                    <TableRow key={rec.id}>
                      <TableCell className="font-medium">{rec.product}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
                          {rec.confidence}%
                        </Badge>
                      </TableCell>
                      <TableCell>{rec.skinType}</TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-1">
                          {rec.ingredients.map((ingredient, index) => (
                            <Badge key={index} variant="secondary" className="text-xs">
                              {ingredient}
                            </Badge>
                          ))}
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge className={`${getStatusColor(rec.status)} text-white`}>
                          {rec.status}
                        </Badge>
                      </TableCell>
                      <TableCell>{rec.date}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}